name: Deploy to AWS S3

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: NodeJS Setup
        uses: actions/setup-node@v4
        with:
          node-version: ${{ secrets.NODE_VERSION }}
      
      - name: Install Dependencies
        run: npm install
      
      - name: App Build
        run: npm run build
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: us-east-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: Deploy AWS S3
        run: aws s3 sync dist s3://petfy.comm.br --delete
